### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by webmeister2** [carlinyuen/ChromeAutoTextExpander#10]
I would like to have more instructions/directions on how to use this - I must be overlooking them. It worked good in the github form name box, but I cannot get this to work in Outlook or Gmail message field...

thank you

**Comment by carlinyuen** [comment]
Hey @webmeister2, some sites are unfortunately not supported, but this should work in most textfields and textareas on sites. I've just rolled out a new version that supports Gmail new message popups and the reply fields too, so hopefully you should see this working now. Let me know if that's not the case!
