### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by fbm-static** [carlinyuen/ChromeAutoTextExpander#13]
I immediately get shown the options page but I don't know what the keyboard shortcut is.

**Comment by carlinyuen** [comment]
Hey Xof, in the options page, you should set up some shortcuts and save
them, and then you can test the shortcuts in the demo area. When you add a
new shortcut, the textfield on the left is the shortcut, and the textarea
to the right is the expanded text. Give that a shot and let me know if you
have any issues!


*. Carlin*
............................................
Product . Design . Development
e : email.me@carlinyuen.com
# : +1 (234) 567-9763
