### ISSUE TITLE
No longer works in Zendesk 

### ISSUE THREAD

**Issue by adelo5891** [carlinyuen/ChromeAutoTextExpander#18]
When I was updates to v.1.9.2, I am now not able to use it in Zendesk. Specifically, it doesn't work in the "Description" section of Zendesk where you actually type your responses.  It does still work in the "Subject" area.

**Comment by adelo5891** [comment]
Update: we found out that this is only a problem if you have "Rich Content" enabled in Zendesk. When we turned that off, the Text Expander worked again. Not a great long term solution because we liked Rich Content, but it'll work for now.

**Comment by jaumebn** [comment]
Hi!
Same happening here. If I download and install the code [at this point in the history](https://github.com/carlinyuen/ChromeAutoTextExpander/tree/d37ac409c02d5b59267e9b61d1a08cbf6e4be841) it works fine. It's version 2.0.0 without version 1.9.2 in between.

**Comment by carlinyuen** [comment]
@takeo helped with submitting and testing the code for the Zendesk wysiwyg editor. Can you help us take a look here to see why the fix isn't working?

**Comment by takeo** [comment]
The fix I did was for Zendesk Inbox, which uses a different editor. I'll take a look, we should be able to conditionally add the fix. We'll just have to do it based on something besides the zendesk.com domain.

**Comment by carlinyuen** [comment]
Hey folks, closing this one out since I believe we have this one resolved now. :) Please reopen if it's still not working.
