### ISSUE TITLE
Content of a paste has different color than rest of text although it should have no formatting

### ISSUE THREAD

**Issue by iwangu** [carlinyuen/ChromeAutoTextExpander#39]
Content of a paste via Autotextexpander has violet color although it should have no formatting:

<img width="265" alt="screen shot 2017-12-06 at 08 58 31" src="https://user-images.githubusercontent.com/7472642/33650860-02cb2454-da64-11e7-8d18-7076bcb47cad.png">

**Comment by iwangu** [comment]
This seems to happen not all the time. Not sure what the problem is here since the snippet clearly has no formatting.

**Comment by carlinyuen** [comment]
Hey Iwan, this might just be related to Gmail (presumably you're using it in Gmail). Gmail has an auto-coloring feature that will color text that was previously used in the email thread in purple (but I believe it's visible only to you?). If you take that same email and forward it to someone else who was never on the email thread, I don't believe they'll see that purple. Please reopen if you find out that this is not the issue!
